url: "https://restaurantjericho.com" # the base hostname & protocol for your site, e.g. http://example.com
title: "Restaurant Jericho" # the name of your site, e.g. ACME Corp.
permalink: /journal/:title
plugins:
  - jekyll-postcss
  - jekyll-minifier
image_base:  https://jericho.imgix.net/
exclude:
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
